spring.application.name=pokecardstore

# ============================================================
# CONFIGURACIÓN DE LA BASE DE DATOS POSTGRESQL
# ============================================================

# Claves Stripe (modo test)
stripe.secret.key=${STRIPE_SECRET_KEY:sk_test_dummy}



# URL de conexión a PostgreSQL
# Formato: jdbc:postgresql://[host]:[puerto]/[nombre_bd]
#spring.datasource.url=jdbc:postgresql://dpg-d4ocv8q4d50c738ps4fg-a.oregon-postgres.render.com:5432/pokecardstore


# Usuario de PostgreSQL
#spring.datasource.username=pokecardstore_user

# Contraseña de PostgreSQL
#spring.datasource.password=ipKreh89UqZflJWJErC6fvGxdFIpJ7f0

spring.datasource.url=jdbc:postgresql://localhost:5432/pokecardstore
spring.datasource.username=pokecardstore_user
spring.datasource.password=pokecardstore_pass





# Driver JDBC de PostgreSQL (se detecta automáticamente)
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================================
# CONFIGURACIÓN DE JPA/HIBERNATE
# ============================================================

# Dialecto de PostgreSQL para Hibernate (OPCIONAL - Spring Boot lo detecta automáticamente)
# Puedes comentar esta línea, Spring Boot 3.5 detecta el dialecto basándose en el driver
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Estrategia de generación/actualización del esquema de BD
# - none: No hace nada (para producción)
# - validate: Solo valida que el esquema coincida
# - update: Actualiza el esquema automáticamente (RECOMENDADO para desarrollo)
# - create: Crea el esquema desde cero (destruye datos existentes)
# - create-drop: Crea al iniciar, destruye al cerrar
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola (útil para debugging)
spring.jpa.show-sql=true

# Formatear las consultas SQL para mejor legibilidad
spring.jpa.properties.hibernate.format_sql=true

# ============================================================
# CONFIGURACIÓN DEL SERVIDOR
# ============================================================

# Puerto del servidor (por defecto es 8080)
server.port=8080

# ============================================================
# CONFIGURACIÓN DE LOGGING
# ============================================================

# Nivel de logging para SQL (DEBUG para ver queries, INFO para producción)
logging.level.org.hibernate.SQL=DEBUG

# Mostrar los valores de los parámetros en las consultas SQL
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Nivel de logging para tu aplicación
logging.level.com.universidad.productosapi=DEBUG


# JWT Configuration
jwt.secret=Nf72KpA9xQmL48vZsP1rC6tBqW9uH3yTgR5eV8bM2nJ4kL7wXcD6sQ1pF8zB3a
jwt.expiration=3600000


#OBSERVABILIDAD - ACTUATOR / PROMETHEUS

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
